project_id = "ariete-bank-portal"

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080/set-password", "http://127.0.0.1:8080/set-password"]

[functions.get-bank-accounts]
verify_jwt = false

[functions.update-bank-account-status]
verify_jwt = false

[functions.get-banks]
verify_jwt = false

[functions.get-users]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.bulk-invite]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
